// ===== Template Engine & Script Builder =====

function buildScriptFromConfig(config) {
    const sections = [];

    // Header
    sections.push(generateHeader());

    // Safety checks
    sections.push(generateSafetyChecks());

    // Partitioning
    sections.push(generatePartitionSection(config));

    // Filesystem
    sections.push(generateFilesystemSection(config));

    // Base installation
    sections.push(generateBaseInstall(config));

    // Kernel
    sections.push(generateKernelSection(config));

    // Desktop Environment / Window Manager
    if (config.desktop_environment !== 'none') {
        sections.push(generateDesktopSection(config));
    }

    // GPU Drivers
    if (config.gpu_driver !== 'none') {
        sections.push(generateGPUSection(config));
    }

    // Additional packages
    if (config.package_groups && config.package_groups.length > 0) {
        sections.push(generatePackagesSection(config));
    }

    // User creation and finalization
    sections.push(generateFinalization());

    return sections.join('\n\n');
}

function generateHeader() {
    const date = new Date().toISOString().split('T')[0];
    return `#!/bin/bash
# ============================================
# Arch Linux Installation Script
# Generated by Arch-Builder
# Date: ${date}
# ============================================
# WARNING: This script will modify your disk!
# Please review before executing
# ============================================

set -e  # Exit on error
set -u  # Exit on undefined variable

# Color codes
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "\${BLUE}[INFO]\${NC} $1"
}

log_success() {
    echo -e "\${GREEN}[SUCCESS]\${NC} $1"
}

log_warning() {
    echo -e "\${YELLOW}[WARNING]\${NC} $1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} $1"
}`;
}

function generateSafetyChecks() {
    return `# ============================================
# Safety Checks
# ============================================

log_info "Performing safety checks..."

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Check if booted in UEFI mode (if applicable)
if [ -d /sys/firmware/efi/efivars ]; then
    log_info "UEFI mode detected"
    UEFI_MODE=true
else
    log_info "BIOS/Legacy mode detected"
    UEFI_MODE=false
fi

# Update system clock
log_info "Updating system clock..."
timedatectl set-ntp true

log_success "Safety checks completed"`;
}

function generatePartitionSection(config) {
    const disk = config.disk_device || '/dev/sda';
    const scheme = config.partition_scheme || 'auto-gpt';

    let script = `# ============================================
# Disk Partitioning
# ============================================

log_info "Detecting target disk..."

if [[ "${disk}" == "en-buyuk" ]]; then
    log_info "Finding the largest block device..."
    DISK="/dev/$(lsblk -bndo NAME,SIZE | sort -rnk2 | head -1 | awk '{print $1}')"
    log_info "Largest disk found: $DISK"
else
    DISK="${disk}"
fi

log_warning "This will ERASE ALL DATA on $DISK"
read -p "Continue? (yes/no): " confirm
if [[ "$confirm" != "yes" ]]; then
    log_error "Installation cancelled by user"
    exit 1
fi

log_info "Partitioning $DISK..."
`;

    if (scheme === 'auto-gpt') {
        script += `
# GPT/UEFI partitioning
parted -s "$DISK" mklabel gpt
parted -s "$DISK" mkpart primary fat32 1MiB 512MiB
parted -s "$DISK" set 1 esp on
parted -s "$DISK" mkpart primary ext4 512MiB 100%

# Set partition variables
if [[ "$DISK" =~ "nvme" ]]; then
    BOOT_PART="\${DISK}p1"
    ROOT_PART="\${DISK}p2"
else
    BOOT_PART="\${DISK}1"
    ROOT_PART="\${DISK}2"
fi

log_success "GPT partitions created"`;
    } else if (scheme === 'auto-mbr') {
        script += `
# MBR/Legacy partitioning
parted -s "$DISK" mklabel msdos
parted -s "$DISK" mkpart primary ext4 1MiB 512MiB
parted -s "$DISK" set 1 boot on
parted -s "$DISK" mkpart primary ext4 512MiB 100%

if [[ "$DISK" =~ "nvme" ]]; then
    BOOT_PART="\${DISK}p1"
    ROOT_PART="\${DISK}p2"
else
    BOOT_PART="\${DISK}1"
    ROOT_PART="\${DISK}2"
fi

log_success "MBR partitions created"`;
    }

    return script;
}

function generateFilesystemSection(config) {
    const fs = config.filesystem || 'btrfs';
    const swapSize = config.swap_size || '4';

    let script = `# ============================================
# Filesystem Creation
# ============================================

log_info "Creating filesystems..."

# Format boot partition
if [[ "$UEFI_MODE" == true ]]; then
    mkfs.fat -F32 "$BOOT_PART"
else
    mkfs.ext4 "$BOOT_PART"
fi
`;

    if (fs === 'btrfs') {
        script += `
# Format root with Btrfs
mkfs.btrfs -f "$ROOT_PART"

# Mount and create subvolumes
mount "$ROOT_PART" /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots
umount /mnt

# Mount subvolumes
mount -o noatime,compress=zstd,subvol=@ "$ROOT_PART" /mnt
mkdir -p /mnt/{home,.snapshots,boot}
mount -o noatime,compress=zstd,subvol=@home "$ROOT_PART" /mnt/home
mount -o noatime,compress=zstd,subvol=@snapshots "$ROOT_PART" /mnt/.snapshots`;
    } else if (fs === 'ext4') {
        script += `
# Format root with Ext4
mkfs.ext4 "$ROOT_PART"
mount "$ROOT_PART" /mnt
mkdir -p /mnt/boot`;
    } else if (fs === 'xfs') {
        script += `
# Format root with XFS
mkfs.xfs -f "$ROOT_PART"
mount "$ROOT_PART" /mnt
mkdir -p /mnt/boot`;
    } else if (fs === 'f2fs') {
        script += `
# Format root with F2FS
mkfs.f2fs -f "$ROOT_PART"
mount "$ROOT_PART" /mnt
mkdir -p /mnt/boot`;
    }

    script += `

# Mount boot partition
mount "$BOOT_PART" /mnt/boot
`;

    if (swapSize !== '0') {
        script += `
# Create swap file
log_info "Creating ${swapSize}GB swap file..."
dd if=/dev/zero of=/mnt/swapfile bs=1G count=${swapSize} status=progress
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile
`;
    }

    script += `
log_success "Filesystems created and mounted"`;

    return script;
}

function generateBaseInstall(config) {
    return `# ============================================
# Base System Installation
# ============================================

log_info "Installing base system..."

pacstrap /mnt base linux-firmware

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

log_success "Base system installed"`;
}

function generateKernelSection(config) {
    const kernel = config.kernel || 'linux';

    return `# ============================================
# Kernel Installation
# ============================================

log_info "Installing ${kernel} kernel..."

arch-chroot /mnt pacman -S --noconfirm ${kernel} ${kernel}-headers

# Install microcode
if grep -q "GenuineIntel" /proc/cpuinfo; then
    log_info "Installing Intel microcode..."
    arch-chroot /mnt pacman -S --noconfirm intel-ucode
elif grep -q "AuthenticAMD" /proc/cpuinfo; then
    log_info "Installing AMD microcode..."
    arch-chroot /mnt pacman -S --noconfirm amd-ucode
fi

log_success "Kernel installed"`;
}

function generateDesktopSection(config) {
    const de = config.desktop_environment;

    let script = `# ============================================
# Desktop Environment / Window Manager
# ============================================

log_info "Installing desktop environment: ${de}"
`;

    if (de === 'gnome' || de === 'gnome-full') {
        script += `
arch-chroot /mnt pacman -S --noconfirm gnome gnome-extra gdm networkmanager
arch-chroot /mnt systemctl enable gdm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'gnome-minimal') {
        script += `
arch-chroot /mnt pacman -S --noconfirm gnome-shell gdm networkmanager
arch-chroot /mnt systemctl enable gdm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'kde' || de === 'kde-full') {
        script += `
arch-chroot /mnt pacman -S --noconfirm plasma plasma-wayland-session kde-applications sddm networkmanager
arch-chroot /mnt systemctl enable sddm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'kde-plasma') {
        script += `
arch-chroot /mnt pacman -S --noconfirm plasma-desktop sddm networkmanager
arch-chroot /mnt systemctl enable sddm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'xfce') {
        script += `
arch-chroot /mnt pacman -S --noconfirm xfce4 xfce4-goodies lightdm lightdm-gtk-greeter networkmanager
arch-chroot /mnt systemctl enable lightdm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'cinnamon') {
        script += `
arch-chroot /mnt pacman -S --noconfirm cinnamon lightdm lightdm-gtk-greeter networkmanager
arch-chroot /mnt systemctl enable lightdm
arch-chroot /mnt systemctl enable NetworkManager`;
    } else if (de === 'hyprland') {
        script += `
arch-chroot /mnt pacman -S --noconfirm hyprland kitty waybar wofi networkmanager`;
    }

    script += `

log_success "Desktop environment installed"`;

    return script;
}

function generateGPUSection(config) {
    const gpu = config.gpu_driver;

    let script = `# ============================================
# GPU Drivers
# ============================================

log_info "Installing GPU drivers..."
`;

    if (gpu === 'nvidia') {
        script += `
arch-chroot /mnt pacman -S --noconfirm nvidia nvidia-utils`;
    } else if (gpu === 'nvidia-lts') {
        script += `
arch-chroot /mnt pacman -S --noconfirm nvidia-lts nvidia-utils`;
    } else if (gpu === 'mesa') {
        script += `
arch-chroot /mnt pacman -S --noconfirm mesa vulkan-radeon vulkan-intel`;
    }

    script += `

log_success "GPU drivers installed"`;

    return script;
}

function generatePackagesSection(config) {
    const groups = config.package_groups || [];

    let script = `# ============================================
# Additional Packages
# ============================================

log_info "Installing additional packages..."
`;

    const packages = [];

    if (groups.includes('base-devel')) {
        packages.push('base-devel');
    }

    if (packages.length > 0) {
        script += `
arch-chroot /mnt pacman -S --noconfirm ${packages.join(' ')}
`;
    }

    script += `
log_success "Additional packages installed"`;

    return script;
}

function generateFinalization() {
    return `# ============================================
# System Configuration
# ============================================

log_info "Configuring system..."

# Set timezone
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
arch-chroot /mnt hwclock --systohc

# Localization
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
echo "tr_TR.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf

# Hostname
read -p "Enter hostname: " hostname
echo "$hostname" > /mnt/etc/hostname
cat > /mnt/etc/hosts << EOF
127.0.0.1    localhost
::1          localhost
127.0.1.1    $hostname.localdomain $hostname
EOF

# Root password
log_info "Set root password:"
arch-chroot /mnt passwd

# Create user
read -p "Enter username: " username
arch-chroot /mnt useradd -m -G wheel,audio,video,storage -s /bin/bash "$username"
log_info "Set password for $username:"
arch-chroot /mnt passwd "$username"

# Enable sudo for wheel group
arch-chroot /mnt sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

# Install and configure bootloader
log_info "Installing bootloader..."
if [[ "$UEFI_MODE" == true ]]; then
    arch-chroot /mnt pacman -S --noconfirm grub efibootmgr
    arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
else
    arch-chroot /mnt pacman -S --noconfirm grub
    arch-chroot /mnt grub-install --target=i386-pc "$DISK"
fi
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

log_success "System configured"

# ============================================
# Installation Complete
# ============================================

log_success "============================================"
log_success "Arch Linux installation completed!"
log_success "============================================"
log_info "Next steps:"
log_info "1. Review any warnings or errors above"
log_info "2. umount -R /mnt"
log_info "3. reboot"
log_info "4. Remove installation media"
log_success "============================================"`;
}

// Export for use in wizard.js
window.buildScriptFromConfig = buildScriptFromConfig;
